name: Publish to github-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install and Builddependencies
        run: |
          python -m pip install --upgrade pip && pip install --no-cache-dir poetry
          poetry config virtualenvs.create false && poetry install

      - name: Run
        run: poetry run python main.py all && echo "[create all] success!!"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          keep_files: true
          commit_message: ${{ github.event.head_commit.message }}
